---
# tasks file for purge
    - name: stop all running containers;
      command: "podman stop {{ item }}"
      loop: "{{ containers }}"

    - name: remove all containers
      command: "podman rm {{ item }}"
      loop: "{{ containers }}"

    - name: remove folders
      file:
        path: "{{ item }}"
        state: absent
      loop: "{{ folders }}"

    - name: remove lvs
      lvol:
        vg: ceph-vg
        lv: "{{ item }}"
        state: absent
        force: yes
      loop: "{{ lvms }}"

    - name: remvoe VG
      lvg:
        vg: ceph-vg
        state: absent
        force: yes
