---
# vars file for containers

containers:
  - ceph-mon
  - ceph-mgr
  - ceph-rgw
  - osd1
  - osd2
  - osd3
  - osd4
  - osd5
folders:
  - /etc/ceph
  - /var/lib/ceph
  - /var/run/ceph
  - /var/log/ceph
lvms:
  - ceph-osd-lvm-0
  - ceph-osd-lvm-1
  - ceph-osd-lvm-2
  - ceph-osd-lvm-3
  - ceph-osd-lvm-4
  - ceph-osd-lvm-5
shell:
  - roles/containers/files/lvm.sh
  - roles/containers/files//de-map
  - roles/containers/files//auth.sh
  - roles/containers/files//crush.sh
  - roles/containers/files//post.sh
packages:
  - lvm2
  - podman
